# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDweb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDweb

  target 'SDwebTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDwebUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage'
pod 'SDWebImage/GIF'
end
